CREATE TABLE tb_clubes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nome_clube VARCHAR(255),
                           federacao VARCHAR(255),
                           pais VARCHAR(255),
                           ano_de_criacao INT
);

CREATE TABLE tb_cadastro (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255),
                             email VARCHAR(255),
                             posicao VARCHAR(50),
                             nacionalidade VARCHAR(255),
                             numero_da_camisa INT,
                             idade INT,
                             clube_id BIGINT,
                             CONSTRAINT fk_jogador_clube FOREIGN KEY (clube_id) REFERENCES tb_clubes(id)
);